// apps/guitar/lib/curriculum.ts
// 60-day fretboard mastery — zone-by-zone with dots as landmarks

export type StringFocus = "all" | "high" | "low";
export type NoteFilter = "all" | "natural";
export type LessonMode = "learn" | "quiz";

export interface Lesson {
  day: number;
  title: string;
  description: string;
  frets: number[];
  stringFocus: StringFocus;
  noteFilter: NoteFilter;
  mode: LessonMode;
  questionCount: number;
  isGate: boolean;
  passThreshold: number;
}

export interface Section {
  id: number;
  title: string;
  subtitle: string;
  days: Lesson[];
}

const R = (start: number, end: number): number[] =>
  Array.from({ length: end - start + 1 }, (_, i) => start + i);

export const CURRICULUM: Section[] = [
  // ── Section 1: First Position (0-4) · dot at 3 ─────────
  {
    id: 1,
    title: "First Position",
    subtitle: "Frets 0-4",
    days: [
      {
        day: 1,
        title: "Open Strings",
        description: "E A D G B E",
        frets: [0],
        stringFocus: "all",
        noteFilter: "natural",
        mode: "learn",
        questionCount: 0,
        isGate: false,
        passThreshold: 0,
      },
      {
        day: 2,
        title: "Open Strings Quiz",
        description: "Open strings, no notes shown.",
        frets: [0],
        stringFocus: "all",
        noteFilter: "natural",
        mode: "quiz",
        questionCount: 10,
        isGate: false,
        passThreshold: 0,
      },
      {
        day: 3,
        title: "Fret 1",
        description: "F, A#, D#, G#, C, F",
        frets: [1],
        stringFocus: "all",
        noteFilter: "all",
        mode: "learn",
        questionCount: 0,
        isGate: false,
        passThreshold: 0,
      },
      {
        day: 4,
        title: "Fret 1 Quiz",
        description: "Frets 0-1.",
        frets: [0, 1],
        stringFocus: "all",
        noteFilter: "all",
        mode: "quiz",
        questionCount: 10,
        isGate: false,
        passThreshold: 0,
      },
      {
        day: 5,
        title: "Fret 2",
        description: "F#, B, E, A, C#, F#",
        frets: [2],
        stringFocus: "all",
        noteFilter: "all",
        mode: "learn",
        questionCount: 0,
        isGate: false,
        passThreshold: 0,
      },
      {
        day: 6,
        title: "Fret 2 Quiz",
        description: "Frets 0-2.",
        frets: R(0, 2),
        stringFocus: "all",
        noteFilter: "all",
        mode: "quiz",
        questionCount: 10,
        isGate: false,
        passThreshold: 0,
      },
      {
        day: 7,
        title: "Fret 3 — Dot",
        description: "G, C, F, A#, D, G. First dot marker.",
        frets: [3],
        stringFocus: "all",
        noteFilter: "all",
        mode: "learn",
        questionCount: 0,
        isGate: false,
        passThreshold: 0,
      },
      {
        day: 8,
        title: "Fret 3 Quiz",
        description: "Frets 0-3.",
        frets: R(0, 3),
        stringFocus: "all",
        noteFilter: "all",
        mode: "quiz",
        questionCount: 10,
        isGate: false,
        passThreshold: 0,
      },
      {
        day: 9,
        title: "Fret 4",
        description: "G#, C#, F#, B, D#, G#. Between dots 3 and 5.",
        frets: [4],
        stringFocus: "all",
        noteFilter: "all",
        mode: "learn",
        questionCount: 0,
        isGate: false,
        passThreshold: 0,
      },
      {
        day: 10,
        title: "Fret 4 Quiz",
        description: "Frets 0-4.",
        frets: R(0, 4),
        stringFocus: "all",
        noteFilter: "all",
        mode: "quiz",
        questionCount: 10,
        isGate: false,
        passThreshold: 0,
      },
      {
        day: 11,
        title: "High Strings (0-4)",
        description: "Strings e, B, G only.",
        frets: R(0, 4),
        stringFocus: "high",
        noteFilter: "all",
        mode: "quiz",
        questionCount: 10,
        isGate: false,
        passThreshold: 0,
      },
      {
        day: 12,
        title: "Low Strings (0-4)",
        description: "Strings D, A, E only.",
        frets: R(0, 4),
        stringFocus: "low",
        noteFilter: "all",
        mode: "quiz",
        questionCount: 10,
        isGate: false,
        passThreshold: 0,
      },
      {
        day: 13,
        title: "Natural Notes (0-4)",
        description: "No sharps/flats.",
        frets: R(0, 4),
        stringFocus: "all",
        noteFilter: "natural",
        mode: "quiz",
        questionCount: 10,
        isGate: false,
        passThreshold: 0,
      },
      {
        day: 14,
        title: "Gate: First Position",
        description:
          "Frets 0-4, all strings, all notes. 15 questions. 80% to pass.",
        frets: R(0, 4),
        stringFocus: "all",
        noteFilter: "all",
        mode: "quiz",
        questionCount: 15,
        isGate: true,
        passThreshold: 0.8,
      },
    ],
  },

  // ── Section 2: Middle Neck (5-8) · dots at 5, 7 ─────────
  {
    id: 2,
    title: "Middle Neck",
    subtitle: "Frets 5-8",
    days: [
      {
        day: 15,
        title: "Fret 5 — Dot",
        description: "A, D, G, C, E, A. Same letter pattern as open strings.",
        frets: [5],
        stringFocus: "all",
        noteFilter: "all",
        mode: "learn",
        questionCount: 0,
        isGate: false,
        passThreshold: 0,
      },
      {
        day: 16,
        title: "Fret 5 Quiz",
        description: "Frets 0-5.",
        frets: R(0, 5),
        stringFocus: "all",
        noteFilter: "all",
        mode: "quiz",
        questionCount: 10,
        isGate: false,
        passThreshold: 0,
      },
      {
        day: 17,
        title: "Fret 6",
        description: "A#, D#, G#, C#, F, A#. Between dots 5 and 7.",
        frets: [6],
        stringFocus: "all",
        noteFilter: "all",
        mode: "learn",
        questionCount: 0,
        isGate: false,
        passThreshold: 0,
      },
      {
        day: 18,
        title: "Fret 6 Quiz",
        description: "Frets 0-6.",
        frets: R(0, 6),
        stringFocus: "all",
        noteFilter: "all",
        mode: "quiz",
        questionCount: 10,
        isGate: false,
        passThreshold: 0,
      },
      {
        day: 19,
        title: "Fret 7 — Dot",
        description: "B, E, A, D, F#, B.",
        frets: [7],
        stringFocus: "all",
        noteFilter: "all",
        mode: "learn",
        questionCount: 0,
        isGate: false,
        passThreshold: 0,
      },
      {
        day: 20,
        title: "Fret 7 Quiz",
        description: "Frets 5, 7.",
        frets: [5, 7],
        stringFocus: "all",
        noteFilter: "all",
        mode: "quiz",
        questionCount: 10,
        isGate: false,
        passThreshold: 0,
      },
      {
        day: 21,
        title: "Fret 8",
        description: "C, F, A#, D#, G, C. Before dot 9.",
        frets: [8],
        stringFocus: "all",
        noteFilter: "all",
        mode: "learn",
        questionCount: 0,
        isGate: false,
        passThreshold: 0,
      },
      {
        day: 22,
        title: "Fret 8 Quiz",
        description: "Frets 5-8.",
        frets: R(5, 8),
        stringFocus: "all",
        noteFilter: "all",
        mode: "quiz",
        questionCount: 10,
        isGate: false,
        passThreshold: 0,
      },
      {
        day: 23,
        title: "High Strings (5-8)",
        description: "Strings e, B, G only.",
        frets: R(5, 8),
        stringFocus: "high",
        noteFilter: "all",
        mode: "quiz",
        questionCount: 10,
        isGate: false,
        passThreshold: 0,
      },
      {
        day: 24,
        title: "Low Strings (5-8)",
        description: "Strings D, A, E only.",
        frets: R(5, 8),
        stringFocus: "low",
        noteFilter: "all",
        mode: "quiz",
        questionCount: 10,
        isGate: false,
        passThreshold: 0,
      },
      {
        day: 25,
        title: "Natural Notes (0-8)",
        description: "No sharps/flats.",
        frets: R(0, 8),
        stringFocus: "all",
        noteFilter: "natural",
        mode: "quiz",
        questionCount: 10,
        isGate: false,
        passThreshold: 0,
      },
      {
        day: 26,
        title: "Gate: Middle Neck",
        description:
          "Frets 0-8, all strings, all notes. 15 questions. 80% to pass.",
        frets: R(0, 8),
        stringFocus: "all",
        noteFilter: "all",
        mode: "quiz",
        questionCount: 15,
        isGate: true,
        passThreshold: 0.8,
      },
    ],
  },

  // ── Section 3: Upper Middle (9-12) · dots at 9, 12 ──────
  {
    id: 3,
    title: "Upper Middle",
    subtitle: "Frets 9-12",
    days: [
      {
        day: 27,
        title: "Fret 9 — Dot",
        description: "C#, F#, B, E, G#, C#. All sharped.",
        frets: [9],
        stringFocus: "all",
        noteFilter: "all",
        mode: "learn",
        questionCount: 0,
        isGate: false,
        passThreshold: 0,
      },
      {
        day: 28,
        title: "Fret 9 Quiz",
        description: "Frets 5-9.",
        frets: R(5, 9),
        stringFocus: "all",
        noteFilter: "all",
        mode: "quiz",
        questionCount: 10,
        isGate: false,
        passThreshold: 0,
      },
      {
        day: 29,
        title: "Fret 10",
        description: "D, G, C, F, A, D. Between dots 9 and 12.",
        frets: [10],
        stringFocus: "all",
        noteFilter: "all",
        mode: "learn",
        questionCount: 0,
        isGate: false,
        passThreshold: 0,
      },
      {
        day: 30,
        title: "Fret 10 Quiz",
        description: "Frets 5-10.",
        frets: R(5, 10),
        stringFocus: "all",
        noteFilter: "all",
        mode: "quiz",
        questionCount: 10,
        isGate: false,
        passThreshold: 0,
      },
      {
        day: 31,
        title: "Fret 11",
        description: "D#, G#, C#, F#, A#, D#. One semitone below the octave.",
        frets: [11],
        stringFocus: "all",
        noteFilter: "all",
        mode: "learn",
        questionCount: 0,
        isGate: false,
        passThreshold: 0,
      },
      {
        day: 32,
        title: "Fret 11 Quiz",
        description: "Frets 0-11.",
        frets: R(0, 11),
        stringFocus: "all",
        noteFilter: "all",
        mode: "quiz",
        questionCount: 10,
        isGate: false,
        passThreshold: 0,
      },
      {
        day: 33,
        title: "Fret 12 — Dot",
        description: "E, A, D, G, B, E. Octave — same notes as open strings.",
        frets: [12],
        stringFocus: "all",
        noteFilter: "all",
        mode: "learn",
        questionCount: 0,
        isGate: false,
        passThreshold: 0,
      },
      {
        day: 34,
        title: "Fret 12 Quiz",
        description: "Frets 0-12.",
        frets: R(0, 12),
        stringFocus: "all",
        noteFilter: "all",
        mode: "quiz",
        questionCount: 10,
        isGate: false,
        passThreshold: 0,
      },
      {
        day: 35,
        title: "High Strings (9-12)",
        description: "Strings e, B, G only.",
        frets: R(9, 12),
        stringFocus: "high",
        noteFilter: "all",
        mode: "quiz",
        questionCount: 10,
        isGate: false,
        passThreshold: 0,
      },
      {
        day: 36,
        title: "Low Strings (9-12)",
        description: "Strings D, A, E only.",
        frets: R(9, 12),
        stringFocus: "low",
        noteFilter: "all",
        mode: "quiz",
        questionCount: 10,
        isGate: false,
        passThreshold: 0,
      },
      {
        day: 37,
        title: "Natural Notes (0-12)",
        description: "No sharps/flats.",
        frets: R(0, 12),
        stringFocus: "all",
        noteFilter: "natural",
        mode: "quiz",
        questionCount: 10,
        isGate: false,
        passThreshold: 0,
      },
      {
        day: 38,
        title: "Gate: Half Board",
        description:
          "Frets 0-12, all strings, all notes. 20 questions. 80% to pass.",
        frets: R(0, 12),
        stringFocus: "all",
        noteFilter: "all",
        mode: "quiz",
        questionCount: 20,
        isGate: true,
        passThreshold: 0.8,
      },
    ],
  },

  // ── Section 4: Upper Neck (13-19) · dots at 15, 17, 19 ──
  {
    id: 4,
    title: "Upper Neck",
    subtitle: "Frets 13-19",
    days: [
      {
        day: 39,
        title: "Frets 13-14",
        description:
          "G#, C#, F#, B, D#, G# then A, D, G, C, E, A. Mirrors frets 1-2.",
        frets: R(13, 14),
        stringFocus: "all",
        noteFilter: "all",
        mode: "learn",
        questionCount: 0,
        isGate: false,
        passThreshold: 0,
      },
      {
        day: 40,
        title: "Frets 13-14 Quiz",
        description: "Frets 0-2 + 13-14.",
        frets: [0, 1, 2, 13, 14],
        stringFocus: "all",
        noteFilter: "all",
        mode: "quiz",
        questionCount: 10,
        isGate: false,
        passThreshold: 0,
      },
      {
        day: 41,
        title: "Fret 15 — Dot",
        description: "G, C, F, A#, D, G. Mirrors dot at 3.",
        frets: [15],
        stringFocus: "all",
        noteFilter: "all",
        mode: "learn",
        questionCount: 0,
        isGate: false,
        passThreshold: 0,
      },
      {
        day: 42,
        title: "Fret 15 Quiz",
        description: "Frets 0-4 + 13-15.",
        frets: [0, 3, 4, 13, 14, 15],
        stringFocus: "all",
        noteFilter: "all",
        mode: "quiz",
        questionCount: 10,
        isGate: false,
        passThreshold: 0,
      },
      {
        day: 43,
        title: "Fret 16",
        description: "G#, C#, F#, B, D#, G#. Mirrors fret 4.",
        frets: [16],
        stringFocus: "all",
        noteFilter: "all",
        mode: "learn",
        questionCount: 0,
        isGate: false,
        passThreshold: 0,
      },
      {
        day: 44,
        title: "Fret 16 Quiz",
        description: "Frets 13-16.",
        frets: R(13, 16),
        stringFocus: "all",
        noteFilter: "all",
        mode: "quiz",
        questionCount: 10,
        isGate: false,
        passThreshold: 0,
      },
      {
        day: 45,
        title: "Fret 17 — Dot",
        description: "A, D, G, C, E, A. Mirrors dot at 5.",
        frets: [17],
        stringFocus: "all",
        noteFilter: "all",
        mode: "learn",
        questionCount: 0,
        isGate: false,
        passThreshold: 0,
      },
      {
        day: 46,
        title: "Fret 17 Quiz",
        description: "Frets 13-17.",
        frets: R(13, 17),
        stringFocus: "all",
        noteFilter: "all",
        mode: "quiz",
        questionCount: 10,
        isGate: false,
        passThreshold: 0,
      },
      {
        day: 47,
        title: "Frets 18-19",
        description: "Dot at 19.",
        frets: R(18, 19),
        stringFocus: "all",
        noteFilter: "all",
        mode: "quiz",
        questionCount: 10,
        isGate: false,
        passThreshold: 0,
      },
      {
        day: 48,
        title: "Natural Notes (0-19)",
        description: "Full board, no sharps/flats. 15 questions.",
        frets: R(0, 19),
        stringFocus: "all",
        noteFilter: "natural",
        mode: "quiz",
        questionCount: 15,
        isGate: false,
        passThreshold: 0,
      },
      {
        day: 49,
        title: "Review: Upper Neck",
        description: "Frets 0-19, all notes. 15 questions.",
        frets: R(0, 19),
        stringFocus: "all",
        noteFilter: "all",
        mode: "quiz",
        questionCount: 15,
        isGate: false,
        passThreshold: 0,
      },
      {
        day: 50,
        title: "Gate: Upper Neck",
        description:
          "All 20 frets, all strings, all notes. 20 questions. 80% to pass.",
        frets: R(0, 19),
        stringFocus: "all",
        noteFilter: "all",
        mode: "quiz",
        questionCount: 20,
        isGate: true,
        passThreshold: 0.8,
      },
    ],
  },

  // ── Section 5: Synthesis & Speed (51-60) ─────────────────
  {
    id: 5,
    title: "Synthesis",
    subtitle: "Full board fluency",
    days: [
      {
        day: 51,
        title: "High Strings (0-19)",
        description: "Strings e, B, G. 15 questions.",
        frets: R(0, 19),
        stringFocus: "high",
        noteFilter: "all",
        mode: "quiz",
        questionCount: 15,
        isGate: false,
        passThreshold: 0,
      },
      {
        day: 52,
        title: "Low Strings (0-19)",
        description: "Strings D, A, E. 15 questions.",
        frets: R(0, 19),
        stringFocus: "low",
        noteFilter: "all",
        mode: "quiz",
        questionCount: 15,
        isGate: false,
        passThreshold: 0,
      },
      {
        day: 53,
        title: "Same-Note Hunt",
        description:
          "Given a note name, find all occurrences on the board. 15 questions.",
        frets: R(0, 19),
        stringFocus: "all",
        noteFilter: "all",
        mode: "quiz",
        questionCount: 15,
        isGate: false,
        passThreshold: 0,
      },
      {
        day: 54,
        title: "String Sweep: High",
        description: "Sweep each high string 0→19, notes visible.",
        frets: R(0, 19),
        stringFocus: "high",
        noteFilter: "all",
        mode: "learn",
        questionCount: 0,
        isGate: false,
        passThreshold: 0,
      },
      {
        day: 55,
        title: "String Sweep: Low",
        description: "Sweep each low string 0→19, notes visible.",
        frets: R(0, 19),
        stringFocus: "low",
        noteFilter: "all",
        mode: "learn",
        questionCount: 0,
        isGate: false,
        passThreshold: 0,
      },
      {
        day: 56,
        title: "Natural Notes (0-19)",
        description: "Full board, no sharps/flats. 20 questions.",
        frets: R(0, 19),
        stringFocus: "all",
        noteFilter: "natural",
        mode: "quiz",
        questionCount: 20,
        isGate: false,
        passThreshold: 0,
      },
      {
        day: 57,
        title: "All Notes (0-19)",
        description: "Full board, all notes. 25 questions.",
        frets: R(0, 19),
        stringFocus: "all",
        noteFilter: "all",
        mode: "quiz",
        questionCount: 25,
        isGate: false,
        passThreshold: 0,
      },
      {
        day: 58,
        title: "Speed Round",
        description: "Full board, all notes. 30 questions.",
        frets: R(0, 19),
        stringFocus: "all",
        noteFilter: "all",
        mode: "quiz",
        questionCount: 30,
        isGate: false,
        passThreshold: 0,
      },
      {
        day: 59,
        title: "Practice Run",
        description: "Full board, all notes. 30 questions.",
        frets: R(0, 19),
        stringFocus: "all",
        noteFilter: "all",
        mode: "quiz",
        questionCount: 30,
        isGate: false,
        passThreshold: 0,
      },
      {
        day: 60,
        title: "Final Exam",
        description: "30 questions, full board, all notes. 80% to complete.",
        frets: R(0, 19),
        stringFocus: "all",
        noteFilter: "all",
        mode: "quiz",
        questionCount: 30,
        isGate: true,
        passThreshold: 0.8,
      },
    ],
  },
];
