// apps/guitar/lib/curriculum.ts
// 60-day fretboard mastery — zone-by-zone with dots as landmarks
// Every day is a gate: linear progression, pass to unlock the next day.

import type { ChordGroupKey } from "@/app/components/chords";

export type StringFocus = "all" | "high" | "low";
export type NoteFilter = "all" | "natural";
export type LessonMode = "learn" | "quiz" | "review";
export type ContentType = "note" | "chord" | "mixed";

export interface ReviewScope {
  type: "note" | "chord";
  frets?: number[];
  stringFocus?: StringFocus;
  noteFilter?: NoteFilter;
  chordGroups?: ChordGroupKey[];
}

export interface Lesson {
  day: number;
  title: string;
  description: string;
  frets: number[];
  stringFocus: StringFocus;
  noteFilter: NoteFilter;
  contentType?: ContentType;
  mode: LessonMode;
  chordGroup?: ChordGroupKey | ChordGroupKey[];
  reviewScopes?: ReviewScope[];
  questionCount: number;
  learnCount?: number;
  isGate: true;
  passThreshold: number;
}

const R = (start: number, end: number): number[] =>
  Array.from({ length: end - start + 1 }, (_, i) => start + i);

export const ALL_LESSONS: Lesson[] = [
  // ── Section 1: First Position (0-4) · dot at 3 ─────────
  {
    day: 1,
    title: "Open Strings",
    description: "E A D G B E — learn each open string, then a 10-question quiz.",
    frets: [0],
    stringFocus: "all",
    noteFilter: "natural",
    mode: "learn",
    questionCount: 10,
    isGate: true,
    passThreshold: 0.8,
  },
  {
    day: 2,
    title: "Fret 1",
    description: "F, A#, D#, G#, C, F — learn + quiz.",
    frets: [1],
    stringFocus: "all",
    noteFilter: "all",
    mode: "learn",
    questionCount: 10,
    isGate: true,
    passThreshold: 0.8,
  },
  {
    day: 3,
    title: "Fret 2",
    description: "F#, B, E, A, C#, F# — learn + quiz.",
    frets: [2],
    stringFocus: "all",
    noteFilter: "all",
    mode: "learn",
    questionCount: 10,
    isGate: true,
    passThreshold: 0.8,
  },
  {
    day: 4,
    title: "Open Major I",
    description: "Learn C, A, G major chord shapes, then take a chord quiz.",
    frets: [],
    stringFocus: "all",
    noteFilter: "all",
    contentType: "chord",
    mode: "learn",
    chordGroup: "open-major-i",
    questionCount: 10,
    isGate: true,
    passThreshold: 0.8,
  },
  {
    day: 5,
    title: "Open Major I Quiz",
    description: "Identify all 5 open major chords: C, A, G, E, D.",
    frets: [],
    stringFocus: "all",
    noteFilter: "all",
    contentType: "chord",
    mode: "quiz",
    chordGroup: "open-major",
    questionCount: 30,
    isGate: true,
    passThreshold: 0.8,
  },
  {
    day: 6,
    title: "Open Major II",
    description: "Learn E, D major chord shapes, then take a chord quiz.",
    frets: [],
    stringFocus: "all",
    noteFilter: "all",
    contentType: "chord",
    mode: "learn",
    chordGroup: "open-major-ii",
    questionCount: 10,
    isGate: true,
    passThreshold: 0.8,
  },
  {
    day: 7,
    title: "Open Major II Quiz",
    description: "Identify all 5 open major chords: C, A, G, E, D.",
    frets: [],
    stringFocus: "all",
    noteFilter: "all",
    contentType: "chord",
    mode: "quiz",
    chordGroup: "open-major",
    questionCount: 30,
    isGate: true,
    passThreshold: 0.8,
  },
  {
    day: 8,
    title: "Open Minor",
    description: "Learn Am, Em, Dm chord shapes, then take a chord quiz.",
    frets: [],
    stringFocus: "all",
    noteFilter: "all",
    contentType: "chord",
    mode: "learn",
    chordGroup: "open-minor",
    questionCount: 10,
    isGate: true,
    passThreshold: 0.8,
  },
  {
    day: 9,
    title: "Review: First Steps",
    description: "Mixed review of open strings and frets 0–3.",
    frets: [],
    stringFocus: "all",
    noteFilter: "all",
    mode: "review",
    questionCount: 30,
    isGate: true,
    passThreshold: 0.8,
    reviewScopes: [
      { type: "note", frets: [0, 1, 2, 3], stringFocus: "all", noteFilter: "all" },
    ],
  },
  {
    day: 10,
    title: "Fret 3 — Dot",
    description: "G, C, F, A#, D, G — first dot marker. Learn + quiz.",
    frets: [3],
    stringFocus: "all",
    noteFilter: "all",
    mode: "learn",
    questionCount: 10,
    isGate: true,
    passThreshold: 0.8,
  },
  {
    day: 11,
    title: "Fret 4",
    description: "G#, C#, F#, B, D#, G# — learn + quiz.",
    frets: [4],
    stringFocus: "all",
    noteFilter: "all",
    mode: "learn",
    questionCount: 10,
    isGate: true,
    passThreshold: 0.8,
  },
  {
    day: 12,
    title: "High Strings (0-4)",
    description: "Strings e, B, G only.",
    frets: R(0, 4),
    stringFocus: "high",
    noteFilter: "all",
    mode: "quiz",
    questionCount: 30,
    isGate: true,
    passThreshold: 0.8,
  },
  {
    day: 13,
    title: "Low Strings (0-4)",
    description: "Strings D, A, E only.",
    frets: R(0, 4),
    stringFocus: "low",
    noteFilter: "all",
    mode: "quiz",
    questionCount: 30,
    isGate: true,
    passThreshold: 0.8,
  },
  {
    day: 14,
    title: "Gate: First Position",
    description:
      "Frets 0-4, all strings, all notes. 30 questions. 80% to pass.",
    frets: R(0, 4),
    stringFocus: "all",
    noteFilter: "all",
    mode: "quiz",
    questionCount: 30,
    isGate: true,
    passThreshold: 0.8,
  },

  // ── Section 2: Middle Neck (5-8) · dots at 5, 7 ─────────
  {
    day: 15,
    title: "Fret 5 — Dot",
    description: "A, D, G, C, E, A — learn + quiz.",
    frets: [5],
    stringFocus: "all",
    noteFilter: "all",
    mode: "learn",
    questionCount: 10,
    isGate: true,
    passThreshold: 0.8,
  },
  {
    day: 16,
    title: "Open 7ths I",
    description: "Learn C7, G7, D7, A7 chord shapes, then take a quiz.",
    frets: [],
    stringFocus: "all",
    noteFilter: "all",
    contentType: "chord",
    mode: "learn",
    chordGroup: "open-sevenths-i",
    questionCount: 10,
    isGate: true,
    passThreshold: 0.8,
  },
  {
    day: 17,
    title: "Open 7ths I Quiz",
    description: "Identify C7, G7, D7, A7 chord shapes.",
    frets: [],
    stringFocus: "all",
    noteFilter: "all",
    contentType: "chord",
    mode: "quiz",
    chordGroup: "open-sevenths",
    questionCount: 30,
    isGate: true,
    passThreshold: 0.8,
  },
  {
    day: 18,
    title: "Fret 6",
    description: "A#, D#, G#, C#, F, A# — learn + quiz.",
    frets: [6],
    stringFocus: "all",
    noteFilter: "all",
    mode: "learn",
    questionCount: 10,
    isGate: true,
    passThreshold: 0.8,
  },
  {
    day: 19,
    title: "Open 7ths II",
    description: "Learn E7, Am7, Em7, Dm7 chord shapes, then take a quiz.",
    frets: [],
    stringFocus: "all",
    noteFilter: "all",
    contentType: "chord",
    mode: "learn",
    chordGroup: "open-sevenths-ii",
    questionCount: 10,
    isGate: true,
    passThreshold: 0.8,
  },
  {
    day: 20,
    title: "Open 7ths II Quiz",
    description: "Identify E7, Am7, Em7, Dm7 chord shapes.",
    frets: [],
    stringFocus: "all",
    noteFilter: "all",
    contentType: "chord",
    mode: "quiz",
    chordGroup: "open-sevenths",
    questionCount: 30,
    isGate: true,
    passThreshold: 0.8,
  },
  {
    day: 21,
    title: "Review: First Position",
    description: "Revisit open strings through fret 5 + open major & minor chords.",
    frets: [],
    stringFocus: "all",
    noteFilter: "all",
    mode: "review",
    questionCount: 30,
    isGate: true,
    passThreshold: 0.8,
    reviewScopes: [
      { type: "note", frets: R(0, 5), stringFocus: "all", noteFilter: "all" },
      { type: "chord", chordGroups: ["open-major", "open-minor"] },
    ],
  },
  {
    day: 22,
    title: "Fret 7 — Dot",
    description: "B, E, A, D, F#, B — learn + quiz.",
    frets: [7],
    stringFocus: "all",
    noteFilter: "all",
    mode: "learn",
    questionCount: 10,
    isGate: true,
    passThreshold: 0.8,
  },
  {
    day: 23,
    title: "Fret 8",
    description: "C, F, A#, D#, G, C — learn + quiz.",
    frets: [8],
    stringFocus: "all",
    noteFilter: "all",
    mode: "learn",
    questionCount: 10,
    isGate: true,
    passThreshold: 0.8,
  },
  {
    day: 24,
    title: "Review: Middle Neck",
    description: "Revisit frets 5–8 notes + open 7th chords.",
    frets: [],
    stringFocus: "all",
    noteFilter: "all",
    mode: "review",
    questionCount: 30,
    isGate: true,
    passThreshold: 0.8,
    reviewScopes: [
      { type: "note", frets: R(5, 8), stringFocus: "all", noteFilter: "all" },
      { type: "chord", chordGroups: ["open-sevenths-i", "open-sevenths-ii"] },
    ],
  },
  {
    day: 25,
    title: "Frets 0–8 Quiz",
    description: "Cumulative: frets 0–8, all strings, all notes.",
    frets: R(0, 8),
    stringFocus: "all",
    noteFilter: "all",
    mode: "quiz",
    questionCount: 30,
    isGate: true,
    passThreshold: 0.8,
  },
  {
    day: 26,
    title: "Gate: Middle Neck",
    description:
      "Frets 0-8, all strings, all notes. 30 questions. 80% to pass.",
    frets: R(0, 8),
    stringFocus: "all",
    noteFilter: "all",
    mode: "quiz",
    questionCount: 30,
    isGate: true,
    passThreshold: 0.8,
  },

  // ── Section 3: Upper Middle (9-12) · dots at 9, 12 ──────
  {
    day: 27,
    title: "Fret 9 — Dot",
    description: "C#, F#, B, E, G#, C# — learn + quiz.",
    frets: [9],
    stringFocus: "all",
    noteFilter: "all",
    mode: "learn",
    questionCount: 10,
    isGate: true,
    passThreshold: 0.8,
  },
  {
    day: 28,
    title: "Barre E-Shape Major",
    description: "Learn F, F#, G, A barre chords (E shape), then take a quiz.",
    frets: [],
    stringFocus: "all",
    noteFilter: "all",
    contentType: "chord",
    mode: "learn",
    chordGroup: "barre-e-major",
    questionCount: 10,
    isGate: true,
    passThreshold: 0.8,
  },
  {
    day: 29,
    title: "Barre E-Shape Major Quiz",
    description: "Identify F, F#, G, A barre chords (E shape).",
    frets: [],
    stringFocus: "all",
    noteFilter: "all",
    contentType: "chord",
    mode: "quiz",
    chordGroup: "barre-e-major",
    questionCount: 30,
    isGate: true,
    passThreshold: 0.8,
  },
  {
    day: 30,
    title: "Fret 10",
    description: "D, G, C, F, A, D — learn + quiz.",
    frets: [10],
    stringFocus: "all",
    noteFilter: "all",
    mode: "learn",
    questionCount: 10,
    isGate: true,
    passThreshold: 0.8,
  },
  {
    day: 31,
    title: "Barre E-Shape Minor",
    description: "Learn Fm, F#m, Gm, G#m barre chords (Em shape), then take a quiz.",
    frets: [],
    stringFocus: "all",
    noteFilter: "all",
    contentType: "chord",
    mode: "learn",
    chordGroup: "barre-e-minor",
    questionCount: 10,
    isGate: true,
    passThreshold: 0.8,
  },
  {
    day: 32,
    title: "Fret 11",
    description: "D#, G#, C#, F#, A#, D# — learn + quiz.",
    frets: [11],
    stringFocus: "all",
    noteFilter: "all",
    mode: "learn",
    questionCount: 10,
    isGate: true,
    passThreshold: 0.8,
  },
  {
    day: 33,
    title: "Fret 12 — Dot",
    description: "E, A, D, G, B, E — the octave. Learn + quiz.",
    frets: [12],
    stringFocus: "all",
    noteFilter: "all",
    mode: "learn",
    questionCount: 10,
    isGate: true,
    passThreshold: 0.8,
  },
  {
    day: 34,
    title: "Review: Upper Middle",
    description: "Revisit frets 9–12 notes + barre E-shape + open chords.",
    frets: [],
    stringFocus: "all",
    noteFilter: "all",
    mode: "review",
    questionCount: 30,
    isGate: true,
    passThreshold: 0.8,
    reviewScopes: [
      { type: "note", frets: R(9, 12), stringFocus: "all", noteFilter: "all" },
      { type: "chord", chordGroups: ["barre-e-major", "barre-e-minor", "open-major", "open-minor"] },
    ],
  },
  {
    day: 35,
    title: "High Strings (9-12)",
    description: "Strings e, B, G only.",
    frets: R(9, 12),
    stringFocus: "high",
    noteFilter: "all",
    mode: "quiz",
    questionCount: 30,
    isGate: true,
    passThreshold: 0.8,
  },
  {
    day: 36,
    title: "Low Strings (9-12)",
    description: "Strings D, A, E only.",
    frets: R(9, 12),
    stringFocus: "low",
    noteFilter: "all",
    mode: "quiz",
    questionCount: 30,
    isGate: true,
    passThreshold: 0.8,
  },
  {
    day: 37,
    title: "Natural Notes (0-12)",
    description: "No sharps/flats.",
    frets: R(0, 12),
    stringFocus: "all",
    noteFilter: "natural",
    mode: "quiz",
    questionCount: 30,
    isGate: true,
    passThreshold: 0.8,
  },
  {
    day: 38,
    title: "Gate: Half Board",
    description:
      "Frets 0-12, all strings, all notes. 30 questions. 80% to pass.",
    frets: R(0, 12),
    stringFocus: "all",
    noteFilter: "all",
    mode: "quiz",
    questionCount: 30,
    isGate: true,
    passThreshold: 0.8,
  },

  // ── Section 4: Upper Neck (13-19) · dots at 15, 17, 19 ──
  {
    day: 39,
    title: "Frets 13-14",
    description:
      "G#, C#, F#, B, D#, G# then A, D, G, C, E, A — learn + quiz.",
    frets: R(13, 14),
    stringFocus: "all",
    noteFilter: "all",
    mode: "learn",
    questionCount: 10,
    isGate: true,
    passThreshold: 0.8,
  },
  {
    day: 40,
    title: "Barre A-Shape Major",
    description: "Learn B, C, C#, E barre chords (A shape), then take a quiz.",
    frets: [],
    stringFocus: "all",
    noteFilter: "all",
    contentType: "chord",
    mode: "learn",
    chordGroup: "barre-a-major",
    questionCount: 10,
    isGate: true,
    passThreshold: 0.8,
  },
  {
    day: 41,
    title: "Barre A-Shape Major Quiz",
    description: "Identify B, C, C#, E barre chords (A shape).",
    frets: [],
    stringFocus: "all",
    noteFilter: "all",
    contentType: "chord",
    mode: "quiz",
    chordGroup: "barre-a-major",
    questionCount: 30,
    isGate: true,
    passThreshold: 0.8,
  },
  {
    day: 42,
    title: "Fret 15 — Dot",
    description: "G, C, F, A#, D, G — mirrors dot at 3. Learn + quiz.",
    frets: [15],
    stringFocus: "all",
    noteFilter: "all",
    mode: "learn",
    questionCount: 10,
    isGate: true,
    passThreshold: 0.8,
  },
  {
    day: 43,
    title: "Fret 16",
    description: "G#, C#, F#, B, D#, G# — learn + quiz.",
    frets: [16],
    stringFocus: "all",
    noteFilter: "all",
    mode: "learn",
    questionCount: 10,
    isGate: true,
    passThreshold: 0.8,
  },
  {
    day: 44,
    title: "Review: Barre Chords",
    description: "Revisit frets 9–19 notes + all barre chords.",
    frets: [],
    stringFocus: "all",
    noteFilter: "all",
    mode: "review",
    questionCount: 30,
    isGate: true,
    passThreshold: 0.8,
    reviewScopes: [
      { type: "note", frets: R(9, 19), stringFocus: "all", noteFilter: "all" },
      { type: "chord", chordGroups: ["barre-e-major", "barre-e-minor", "barre-a-major"] },
    ],
  },
  {
    day: 45,
    title: "Fret 17 — Dot",
    description: "A, D, G, C, E, A — mirrors dot at 5. Learn + quiz.",
    frets: [17],
    stringFocus: "all",
    noteFilter: "all",
    mode: "learn",
    questionCount: 10,
    isGate: true,
    passThreshold: 0.8,
  },
  {
    day: 46,
    title: "Frets 18-19 Quiz",
    description: "Dot at 19. All notes at frets 18-19.",
    frets: R(18, 19),
    stringFocus: "all",
    noteFilter: "all",
    mode: "quiz",
    questionCount: 30,
    isGate: true,
    passThreshold: 0.8,
  },
  {
    day: 47,
    title: "Review: All Barre Chords",
    description: "Revisit upper neck notes + every barre chord shape.",
    frets: [],
    stringFocus: "all",
    noteFilter: "all",
    mode: "review",
    questionCount: 30,
    isGate: true,
    passThreshold: 0.8,
    reviewScopes: [
      { type: "note", frets: R(13, 19), stringFocus: "all", noteFilter: "all" },
      { type: "chord", chordGroups: ["barre-e-major", "barre-e-minor", "barre-a-major", "barre-a-minor"] },
    ],
  },
  {
    day: 48,
    title: "Natural Notes (0-19)",
    description: "Full board, no sharps/flats. 30 questions.",
    frets: R(0, 19),
    stringFocus: "all",
    noteFilter: "natural",
    mode: "quiz",
    questionCount: 30,
    isGate: true,
    passThreshold: 0.8,
  },
  {
    day: 49,
    title: "All Notes: Upper Neck",
    description: "Frets 0–19, all notes. 30 questions.",
    frets: R(0, 19),
    stringFocus: "all",
    noteFilter: "all",
    mode: "quiz",
    questionCount: 30,
    isGate: true,
    passThreshold: 0.8,
  },
  {
    day: 50,
    title: "Gate: Upper Neck",
    description:
      "All 20 frets, all strings, all notes. 30 questions. 80% to pass.",
    frets: R(0, 19),
    stringFocus: "all",
    noteFilter: "all",
    mode: "quiz",
    questionCount: 30,
    isGate: true,
    passThreshold: 0.8,
  },

  // ── Section 5: Synthesis & Speed (51-60) ─────────────────
  {
    day: 51,
    title: "String Sweep: High",
    description: "Sweep each high string 0→19, notes visible. Learn + quiz.",
    frets: R(0, 19),
    stringFocus: "high",
    noteFilter: "all",
    mode: "learn",
    questionCount: 10,
    isGate: true,
    passThreshold: 0.8,
  },
  {
    day: 52,
    title: "String Sweep: Low",
    description: "Sweep each low string 0→19, notes visible. Learn + quiz.",
    frets: R(0, 19),
    stringFocus: "low",
    noteFilter: "all",
    mode: "learn",
    questionCount: 10,
    isGate: true,
    passThreshold: 0.8,
  },
  {
    day: 53,
    title: "Chord Recognition",
    description: "Identify chords from all groups: open, 7ths, and barre.",
    frets: [],
    stringFocus: "all",
    noteFilter: "all",
    contentType: "chord",
    mode: "quiz",
    chordGroup: [
      "open-major", "open-minor", "open-sevenths",
      "barre-e-major", "barre-e-minor",
      "barre-a-major", "barre-a-minor",
    ],
    questionCount: 30,
    isGate: true,
    passThreshold: 0.8,
  },
  {
    day: 54,
    title: "High Strings Full Board",
    description: "Strings e, B, G — all 20 frets. 30 questions.",
    frets: R(0, 19),
    stringFocus: "high",
    noteFilter: "all",
    mode: "quiz",
    questionCount: 30,
    isGate: true,
    passThreshold: 0.8,
  },
  {
    day: 55,
    title: "Review: Full Board & Barre",
    description: "Revisit full board notes + all barre chord shapes.",
    frets: [],
    stringFocus: "all",
    noteFilter: "all",
    mode: "review",
    questionCount: 30,
    isGate: true,
    passThreshold: 0.8,
    reviewScopes: [
      { type: "note", frets: R(0, 19), stringFocus: "all", noteFilter: "all" },
      { type: "chord", chordGroups: ["barre-e-major", "barre-e-minor", "barre-a-major", "barre-a-minor"] },
    ],
  },
  {
    day: 56,
    title: "Low Strings Full Board",
    description: "Strings D, A, E — all 20 frets. 30 questions.",
    frets: R(0, 19),
    stringFocus: "low",
    noteFilter: "all",
    mode: "quiz",
    questionCount: 30,
    isGate: true,
    passThreshold: 0.8,
  },
  {
    day: 57,
    title: "Review: All Chords & Board",
    description: "Revisit every chord group + full board note identification.",
    frets: [],
    stringFocus: "all",
    noteFilter: "all",
    mode: "review",
    questionCount: 30,
    isGate: true,
    passThreshold: 0.8,
    reviewScopes: [
      { type: "note", frets: R(0, 19), stringFocus: "all", noteFilter: "all" },
      { type: "chord", chordGroups: ["open-major", "open-minor", "open-sevenths", "barre-e-major", "barre-e-minor", "barre-a-major", "barre-a-minor"] },
    ],
  },
  {
    day: 58,
    title: "All Notes Full Board",
    description: "Full board, all notes. 30 questions.",
    frets: R(0, 19),
    stringFocus: "all",
    noteFilter: "all",
    mode: "quiz",
    questionCount: 30,
    isGate: true,
    passThreshold: 0.8,
  },
  {
    day: 59,
    title: "Speed Round",
    description: "Full board, all notes. 30 questions. Go fast!",
    frets: R(0, 19),
    stringFocus: "all",
    noteFilter: "all",
    mode: "quiz",
    questionCount: 30,
    isGate: true,
    passThreshold: 0.8,
  },
  {
    day: 60,
    title: "Grand Review",
    description: "Everything: all frets, all notes, all chords. 30 questions. 80% to pass.",
    frets: [],
    stringFocus: "all",
    noteFilter: "all",
    contentType: "mixed",
    mode: "review",
    questionCount: 30,
    isGate: true,
    passThreshold: 0.8,
    reviewScopes: [
      { type: "note", frets: R(0, 19), stringFocus: "all", noteFilter: "all" },
      { type: "chord", chordGroups: ["open-major", "open-minor", "open-sevenths", "barre-e-major", "barre-e-minor", "barre-a-major", "barre-a-minor"] },
    ],
  },
];

// Backward-compatible: derive section groupings from the flat list
export interface Section {
  id: number;
  title: string;
  subtitle: string;
  days: Lesson[];
}

export const SECTIONS: Section[] = [
  {
    id: 1,
    title: "First Position",
    subtitle: "Frets 0-4",
    days: ALL_LESSONS.filter((l) => l.day >= 1 && l.day <= 14),
  },
  {
    id: 2,
    title: "Middle Neck",
    subtitle: "Frets 5-8",
    days: ALL_LESSONS.filter((l) => l.day >= 15 && l.day <= 26),
  },
  {
    id: 3,
    title: "Upper Middle",
    subtitle: "Frets 9-12",
    days: ALL_LESSONS.filter((l) => l.day >= 27 && l.day <= 38),
  },
  {
    id: 4,
    title: "Upper Neck",
    subtitle: "Frets 13-19",
    days: ALL_LESSONS.filter((l) => l.day >= 39 && l.day <= 50),
  },
  {
    id: 5,
    title: "Synthesis",
    subtitle: "Full board fluency",
    days: ALL_LESSONS.filter((l) => l.day >= 51 && l.day <= 60),
  },
];

export const TOTAL_DAYS = ALL_LESSONS.length;
